{% set name = "gmmlib" %}
{% set version = "22.5.5" %}

package:
  name: intel-gmmlib
  version: {{ version }}

source:
  url: https://github.com/intel/gmmlib/archive/refs/tags/intel-gmmlib-{{ version }}.tar.gz
  sha256: 08db696071510b7e03aa2d9fb7375c6c35f7c327ecd6747424c664c622bb4377

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage("intel-gmmlib", max_pin="x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make

test:
  commands:
    - test -f ${PREFIX}/lib/libigdgmm${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/intel/gmmlib
  license: MIT
  license_file: LICENSE.md
  license_family: MIT
  summary: Intel(R) Graphics Memory Management Library

extra:
  recipe-maintainers:
    - oleksandr-pavlyk
    - ZzEeKkAa
    - isuruf
